//POST   https://localhost:7106/api/Articulos/
POST http://www.articulosapi.somee.com/api/Articulos

Content-Type: application/json
{
  "ariticuloId": 0,
  "descripcion": "PC Desktop",
  "marca": "Dell",
  "precio": 9000,
  "existencia": 50
}