POST   https://localhost:7106/api/Articulos/
Content-Type: application/json

{
    "ariticuloId": 2,
    "descripcion": "Redmi Note 8",
    "marca": "Xiaomi",
    "precio": 53000.00,
    "existencia": 10.00
}
